[tox]
; envlist = pylint, black
envlist = py{312,313}
skip_missing_interpreters = true

[testenv]
deps =
  coverage
  pytest
commands =
    coverage run --parallel-mode -m pytest {posargs}
    coverage combine
    coverage report -m
    coverage xml

[testenv:ruff]
deps=
    ruff
commands=
    ruff check nectarengine

[testenv:format]
deps=
    ruff
commands=
    ruff format nectarengine
